version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: bookstore
      MYSQL_ROOT_PASSWORD: root
# Remove or comment out:
# ports:
#   - "3306:3306"
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bookstore
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db